---
styleguide: plataformatec/linters
pull_requests:
  enabled: true
engines:
  fixme:
    enabled: true
  eslint:
    enabled: true
  shellcheck:
    enabled: true
  remark-lint:
    enabled: true
  duplication:
    enabled: true
exclude_paths:
 - android/
 - ios/
