language: javascript
branches:
  only:
  - master
cache:
  yarn: true
  directories:
  - node_modules
before_install:
  - nvm install && nvm use
install:
  - npm install
script:
  - npm test
  - npm run lint:check
env:
  global:
  - MONGO_TEST_URL='mongodb://127.0.0.1:27017'
