language: node_js
node_js:
  - "8"
branches:
  only:
  - master
cache:
  yarn: true
  directories:
  - node_modules
before_install:
  - nvm install && nvm use
install:
  - npm install
script:
  - npm run lint:check
  - npm run test:unit
notifications:
    webhooks: https://www.travisbuddy.com/
    on_success: never
